# Generated by Django 5.2.9 on 2026-01-06 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('precipitation', models.FloatField()),
                ('date_checked', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshots', to='weather.city')),
            ],
        ),
        migrations.CreateModel(
            name='RunRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comfort_score', models.IntegerField()),
                ('is_good_for_run', models.BooleanField()),
                ('explanation', models.TextField()),
                ('weather', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='run_recommendation', to='weather.weathersnapshot')),
            ],
        ),
    ]
